
server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본값은 dev
    include: oauth

  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: none        # 공통은 안전하게 none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expire: ${JWT_ACCESS_EXPIRE:3600000}
  refresh-expire: ${JWT_REFRESH_EXPIRE:604800000}
mework.security: INFO

openai:
  secret-key: ${GPT_API_KEY}
  model: gpt-4o
  api-url: https://api.openai.com/v1/chat/completions
  temperature:
    paraphrase: 0.3
    summary: 0.7
  max-tokens: 500
